### ISSUE TITLE
Bring back query from query history 

### ISSUE THREAD

**Issue by stoch** [K2InformaticsGmbH/dderl#352] opened 2017-01-02 12:02 UTC
![image](https://cloud.githubusercontent.com/assets/1941407/21588879/74bb123c-d0eb-11e6-8b35-aa80b2b938c8.png)

Clicking on the blue query should bring back this query into the query editor (after saving the current query on top of the history stack if not already there).

**Comment by acautin** [comment] 2017-01-03 08:48
@stoch is the issue here: queries are not saved in the history if they are not executed ?.

Or was this query not brought back on selection ?.

**Comment by acautin** [comment] 2017-01-17 13:10
Not able to reproduce, will remove the milestone for now and close next milestone if it doesn't appear again.

**Comment by acautin** [comment] 2017-03-07 14:31
closing as unable to reproduce

**Closed by acautin** 2017-03-07 14:31 UTC
Labels: bug
